development:
  adapter: postgresql
  encoding: unicode
  database: pic_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: pic_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost

